# Файл конфигурации системы управления

# Коэффициенты ПИД регулятора угловой скорости по оси X
KpXAngularRate: 0.100
KiXAngularRate: 0.0
KdXAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Y
KpYAngularRate: 20
KiYAngularRate: 0.0
KdYAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Z
KpZAngularRate: 1
KiZAngularRate: 0
KdZAngularRate: 0
# Коэффициенты ПИД регулятора углового положения по оси X
KpXAngle: 0.0100
KiXAngle: 0
KdXAngle: 0.0
# Коэффициенты ПИД регулятора углового положения по оси Y
KpYAngle: 10
KiYAngle: 0.0
KdYAngle: 0.0
# Коэффициенты ПИД регулятора углового положения по оси Z
KpZAngle: 1
KiZAngle: 0.01
KdZAngle: 0.0
# Коэффициенты ПИД регулятора пространственного положения по оси X
KpXPosition: 250
KiXPosition: 1.0
KdXPosition: 1.0
# Коэффициенты ПИД регулятора пространственного положения по оси Y
KpYPosition: 20
KiYPosition: 0.00
KdYPosition: 0.0
# Коэффициенты ПИД регулятора пространственного положения по оси Z
KpZPosition: 250
KiZPosition: 10
KdZPosition: 00

# Ограничение значений выхода ПИД-регулятора по угловому положению
maxCommandAngle: 0.5

minCommandAngle: -0.5
# Ограничения максимального значения выхода ПИД-регулятора по угловой скорости
maxCommandAngularRate: 1

minCommandAngularRate: -1
# Ограничения максимального значения выхода ПИД-регулятора по угловому ускорению
maxCommandAngularAcceleration: 25

minCommandAngularAcceleration: -25
# Ограничение по тяге
maxThrust: 3000
minThrust: 0